### ISSUE TITLE
Documentation doesen't work

### ISSUE THREAD

**Issue by kristijandraca** [grab/grazel#99]
https://grab.github.io/Grazel/ has been down for a few days now.

**Comment by arunsampathkumar-grabtaxi** [comment]
Sorry the latest link is [grab.github.io/grazel/](https://grab.github.io/grazel/) with small `g`. Please note some of the documentation is not up to date with improvements planned for `0.5.0`, it will be ready together with the release.

Closing this, please feel to reopen if you have any other concern.
